language: php

php:
  - 7.1

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
  - mkdir -p build/logs
  - ls -al

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml
  - ./vendor/bin/phpcs --standard=PSR2 src/ -p

after_success:
# Submit coverage report to Coveralls servers, see .coveralls.yml
  - travis_retry php coveralls.phar -v
